services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic
    container_name: borgmatic
    volumes:
      # Sao lưu các thư mục EasyEngine và Docker
      - ${VOLUME_EE_SOURCE}:/mnt/source/easyengine:ro
      - ${VOLUME_DOCKER_VOLUMES}:/mnt/source/volumes:ro
      - ${VOLUME_BORGMATIC_CONFIG_SOURCE}:/mnt/source/borgmatic:ro
      - ${VOLUME_FAIL2BAN_CONFIG_SOURCE}:/mnt/source/fail2ban:ro
      - ${VOLUME_CRONTAB_SOURCE}:/mnt/source/crontab:ro
      # Thư mục khôi phục
      - ${VOLUME_RESTORE_DESTINATION}:/restore
      # Các thư mục quản lý Borg
      - ${VOLUME_BORG_REPOSITORY}:/mnt/borg-repository
      - ${VOLUME_ETC_BORGMATIC}:/etc/borgmatic.d/
      - ${VOLUME_BORG_CONFIG}:/root/.config/borg
      - ${VOLUME_SSH}:/root/.ssh
      - ${VOLUME_BORG_CACHE}:/root/.cache/borg
      # Đồng bộ múi giờ
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - HOST_NAME=${HOST_NAME}
      - BORGBASE_REPO_PATH=${BORGBASE_REPO_PATH}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      global-backend-network:

networks:
  global-backend-network:
    external: true
    name: ee-global-backend-network