name: fail2ban
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./data:/data" # Chứa jails, actions, filters tùy chỉnh & DB
      # Các mount log được lấy từ biến môi trường
      ${FAIL2BAN_LOG_MOUNTS} 
    restart: unless-stopped