name: fail2ban
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host" # Cần để Fail2ban theo dõi và chặn IP trực tiếp
    cap_add:
      - NET_ADMIN # Cho phép quản lý network (ví dụ: cấm IP)
      - NET_RAW # Cho phép thao tác với các gói tin thô
    volumes:
      - "./data:/data" # Lưu cấu hình (jails, actions, filters) và DB của Fail2ban
      - "/opt/easyengine/services/nginx-proxy/logs:/var/log/nginx-proxy:ro" # Mount log Nginx proxy
      - "/opt/easyengine/sites/your-site-1.com/logs/nginx:/var/log/your-site-1.com-nginx:ro" # Mount log Nginx của your-site-1
      # - "/opt/easyengine/sites/your-site-2.com/logs/nginx:/var/log/your-site-2.com-nginx:ro" # Mount log Nginx của your-site-2 (nếu có)

    restart: unless-stopped # Luôn khởi động lại trừ khi bị dừng thủ công hoặc lỗi