#!/bin/sh

COMPOSE_FILE="/opt/fail2ban/docker-compose.yml"

# Nếu lệnh là 'fail2ban-client update', thực hiện cập nhật container
if [ "$1" = "update" ]; then
echo "Checking for Fail2ban updates..."

    # Sử dụng mktemp để tạo file tạm lưu log
    tmp_log=$(mktemp)

    script -q -c "sudo docker compose -f $COMPOSE_FILE pull" /dev/null | tee "$tmp_log"
    # Kiểm tra trong file tạm xem có chữ "Pull complete" không
    if grep -q "Pull complete" "$tmp_log"; then
        echo "------------------------------------------------------"
        echo "New version detected. Recreating Fail2ban container..."
        sudo docker compose -f "$COMPOSE_FILE" up -d
    else
        echo "------------------------------------------------------"
        echo "Fail2ban is already up to date. No restart required."
    fi

    # Xóa file tạm sau khi dùng xong
    rm -f "$tmp_log"
else
    # Giữ nguyên các tham số truyền vào cho fail2ban-client native bên trong container
    # Sử dụng exec -t để hỗ trợ tương tác dòng lệnh
    sudo docker compose \
    -f "$COMPOSE_FILE" \
    exec -t fail2ban \
    fail2ban-client \
    "$@"
fi
