name: Release Crowdsec

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag (e.g., v1.0.1)'
        required: true
        default: 'latest'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Create crowdsec tarball
        run: |
          tar -czvf crowdsec.tar.gz crowdsec/
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || github.event.inputs.tag_name }}
          files: crowdsec.tar.gz
          generate_release_notes: true
